services:
  web:
    build: .
    entrypoint: /app/entrypoint.sh
    volumes:
      - .:/app
      - ./data/web/static:/data/web/static
      - ./data/web/media:/data/web/media
      - ./data/web/log:/data/web/log
    # ports:
    #   - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - rabbitmq
      - mosquitto
      - logstash
    networks:
      - app_network

  db:
    image: postgres:13
    volumes:
      - ./data/postgres/data:/var/lib/postgresql/data/
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      - app_network

  rabbitmq:
    image: rabbitmq:3-management
    env_file:
      - .env
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - app_network

  mosquitto:
    image: eclipse-mosquitto:1.6.15
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./data/mosquitto/data:/mosquitto/data
      - ./data/mosquitto/logs:/mosquitto/log
    networks:
      - app_network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.9
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    volumes:
      - ./data/es_data:/usr/share/elasticsearch/data
    networks:
      - app_network

  logstash:
    image: docker.elastic.co/logstash/logstash:7.17.9
    volumes:
      - ./srv/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    ports:
      - "5044:5044"
      - "9600:9600"
    depends_on:
      - elasticsearch
    networks:
      - app_network

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.9
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    networks:
      - app_network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./srv/nginx.conf:/etc/nginx/nginx.conf
      - ./srv/ssl:/etc/nginx/ssl
      - ./data/web/static:/data/web/static
      - ./data/web/media:/data/web/media
    depends_on:
      - web
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  postgres_data:
  mosquitto_data:
  mosquitto_logs:
  es_data:
