# Generated by Django 4.2.15 on 2024-09-02 19:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MqttTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('content', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='Preset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preset_id', models.CharField(max_length=255, unique=True)),
                ('configuration', models.JSONField()),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Reader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('ip_address', models.GenericIPAddressField()),
                ('port', models.IntegerField()),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('active_preset', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_reader', to='readers.preset')),
            ],
        ),
        migrations.CreateModel(
            name='ReadPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('timeout_seconds', models.IntegerField(default=300)),
                ('readers', models.ManyToManyField(blank=True, related_name='read_points', to='readers.reader')),
            ],
        ),
        migrations.CreateModel(
            name='WebhookTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('content', models.JSONField(default=dict)),
                ('readers', models.ManyToManyField(related_name='webhook_templates', to='readers.reader')),
            ],
        ),
        migrations.CreateModel(
            name='WebhookTemplateApplicationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('success', models.BooleanField(default=False)),
                ('response_message', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('retry', models.BooleanField(default=False)),
                ('reader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhook_application_results', to='readers.reader')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_results', to='readers.webhooktemplate')),
            ],
        ),
        migrations.CreateModel(
            name='TagTraceability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('epc', models.CharField(max_length=256)),
                ('arrived_at', models.DateTimeField(blank=True, null=True)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('departed_at', models.DateTimeField(blank=True, null=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='readers.location')),
                ('read_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='readers.readpoint')),
            ],
        ),
        migrations.CreateModel(
            name='TagEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('epc', models.CharField(max_length=256)),
                ('timestamp', models.DateTimeField()),
                ('antenna_port', models.PositiveIntegerField(blank=True, null=True)),
                ('antenna_name', models.CharField(blank=True, max_length=256, null=True)),
                ('peak_rssi_cdbm', models.IntegerField(blank=True, null=True)),
                ('frequency', models.FloatField(blank=True, null=True)),
                ('transmit_power_cdbm', models.FloatField(blank=True, null=True)),
                ('last_seen_time', models.DateTimeField(blank=True, null=True)),
                ('tid', models.CharField(blank=True, max_length=256, null=True)),
                ('tid_hex', models.CharField(blank=True, max_length=256, null=True)),
                ('rf_phase', models.FloatField(blank=True, null=True)),
                ('tag_data_key', models.CharField(blank=True, max_length=255, null=True)),
                ('tag_data_key_name', models.CharField(blank=True, max_length=255, null=True)),
                ('tag_data_serial', models.CharField(blank=True, max_length=255, null=True)),
                ('reader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='readers.reader')),
            ],
        ),
        migrations.CreateModel(
            name='PresetTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('configuration', models.JSONField()),
                ('readers', models.ManyToManyField(blank=True, related_name='preset_templates', to='readers.reader')),
            ],
        ),
        migrations.AddField(
            model_name='preset',
            name='reader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presets', to='readers.reader'),
        ),
        migrations.CreateModel(
            name='MQTTTemplateApplicationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('success', models.BooleanField(default=False)),
                ('response_message', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('retry', models.BooleanField(default=False)),
                ('reader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mqtt_application_results', to='readers.reader')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_results', to='readers.mqtttemplate')),
            ],
        ),
        migrations.AddField(
            model_name='mqtttemplate',
            name='readers',
            field=models.ManyToManyField(related_name='mqtt_templates', to='readers.reader'),
        ),
    ]
