# Generated by Django 4.2.15 on 2024-08-15 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('ip_address', models.GenericIPAddressField()),
                ('port', models.IntegerField()),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('preset_id', models.CharField(blank=True, default='default', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TagEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('epc', models.CharField(max_length=256)),
                ('timestamp', models.DateTimeField()),
                ('reader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='readers.reader')),
            ],
        ),
    ]
