# Generated by Django 4.2.15 on 2024-08-15 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reader',
            name='preset_id',
            field=models.CharField(default='default', max_length=100),
        ),
    ]
