# Generated by Django 4.2.15 on 2024-08-15 18:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('readers', '0002_alter_reader_preset_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tagevent',
            name='antenna_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tagevent',
            name='antenna_port',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tagevent',
            name='frequency',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tagevent',
            name='last_seen_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tagevent',
            name='peak_rssi_cdbm',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tagevent',
            name='tid',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='tagevent',
            name='tid_hex',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='tagevent',
            name='transmit_power_cdbm',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
