# Generated by Django 4.2.15 on 2024-08-15 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readers', '0003_tagevent_antenna_name_tagevent_antenna_port_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tagevent',
            name='antenna_name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
