# Generated by Django 4.2.15 on 2024-08-26 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('readers', '0004_alter_tagevent_antenna_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reader',
            name='preset_id',
        ),
        migrations.CreateModel(
            name='Preset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preset_id', models.CharField(max_length=255)),
                ('configuration', models.JSONField()),
                ('is_active', models.BooleanField(default=False)),
                ('reader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presets', to='readers.reader')),
            ],
        ),
        migrations.AddField(
            model_name='reader',
            name='active_preset',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_reader', to='readers.preset'),
        ),
    ]
