# Generated by Django 4.2.16 on 2024-09-03 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartreader', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smartreader',
            name='field_delim',
        ),
        migrations.RemoveField(
            model_name='smartreader',
            name='line_end',
        ),
        migrations.AddField(
            model_name='smartreader',
            name='active_plugin',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='smartreader',
            name='antenna_identifier',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='smartreader',
            name='barcode_enable_queue',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='smartreader',
            name='barcode_line_end',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='smartreader',
            name='barcode_process_no_data_string',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='smartreader',
            name='barcode_tcp_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='smartreader',
            name='barcode_tcp_len',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='smartreader',
            name='barcode_tcp_no_data_string',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='smartreader',
            name='barcode_tcp_port',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='smartreader',
            name='cleanup_tag_events_list_batch_on_reload',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='smartreader',
            name='csv_file_format',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='smartreader',
            name='enable_antenna_task',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='smartreader',
            name='enable_barcode_hid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='smartreader',
            name='enable_barcode_serial',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='smartreader',
            name='enable_barcode_tcp',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='smartreader',
            name='enable_external_api_verification',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='smartreader',
            name='enable_opc_ua_client',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='smartreader',
            name='enable_partial_validation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='smartreader',
            name='enable_plugin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='smartreader',
            name='enable_plugin_shipment_verification',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='smartreader',
            name='enable_summary_stream',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='smartreader',
            name='enable_tag_event_stream',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='smartreader',
            name='enable_tag_events_list_batch',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='smartreader',
            name='enable_tag_events_list_batch_publishing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='smartreader',
            name='enable_unique_tag_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='smartreader',
            name='enable_validation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='smartreader',
            name='external_api_verification_auth_login_url',
            field=models.URLField(blank=True, max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='smartreader',
            name='external_api_verification_change_order_status_url',
            field=models.URLField(blank=True, max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='smartreader',
            name='external_api_verification_http_header_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='smartreader',
            name='external_api_verification_http_header_value',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='smartreader',
            name='external_api_verification_publish_data_url',
            field=models.URLField(blank=True, max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='smartreader',
            name='external_api_verification_search_order_url',
            field=models.URLField(blank=True, max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='smartreader',
            name='external_api_verification_search_product_url',
            field=models.URLField(blank=True, max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='smartreader',
            name='filter_tag_events_list_batch_on_change_based_on_antenna_zone',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='smartreader',
            name='group_events_on_inventory_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='smartreader',
            name='gtin_output_type',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='smartreader',
            name='http_authentication_token_api_password_field',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='smartreader',
            name='http_authentication_token_api_password_value',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='smartreader',
            name='http_authentication_token_api_username_field',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='smartreader',
            name='http_authentication_token_api_username_value',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='smartreader',
            name='http_verify_host',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='smartreader',
            name='http_verify_peer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='smartreader',
            name='json_format',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='smartreader',
            name='network_proxy',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='smartreader',
            name='network_proxy_port',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='smartreader',
            name='opc_ua_connection_discovery_address',
            field=models.URLField(blank=True, max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='smartreader',
            name='opc_ua_connection_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='smartreader',
            name='opc_ua_connection_publisher_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='smartreader',
            name='opc_ua_connection_url',
            field=models.URLField(blank=True, max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='smartreader',
            name='opc_ua_data_set_key_frame_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='smartreader',
            name='opc_ua_data_set_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='smartreader',
            name='opc_ua_data_set_writer_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='smartreader',
            name='opc_ua_data_set_writer_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='smartreader',
            name='opc_ua_writer_group_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='smartreader',
            name='opc_ua_writer_group_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='smartreader',
            name='opc_ua_writer_header_layout_uri',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='smartreader',
            name='opc_ua_writer_keep_alive_time',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='smartreader',
            name='opc_ua_writer_max_network_message_size',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='smartreader',
            name='opc_ua_writer_publishing_interval',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='smartreader',
            name='package_headers',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='smartreader',
            name='parse_sgtin_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='smartreader',
            name='parse_sgtin_include_key_type',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='smartreader',
            name='parse_sgtin_include_pure_identity',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='smartreader',
            name='parse_sgtin_include_serial',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='smartreader',
            name='plugin_server',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='smartreader',
            name='positioning_antenna_ports',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='smartreader',
            name='positioning_epcs_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='smartreader',
            name='positioning_epcs_filter',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='smartreader',
            name='positioning_epcs_header_list',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='smartreader',
            name='positioning_expiration_in_sec',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='smartreader',
            name='positioning_report_interval_in_sec',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='smartreader',
            name='publish_full_shipment_validation_list_on_acceptance_threshold',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='smartreader',
            name='publish_single_time_on_acceptance_threshold',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='smartreader',
            name='rci_spot_report_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='smartreader',
            name='rci_spot_report_include_ant',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='smartreader',
            name='rci_spot_report_include_dwn_cnt',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='smartreader',
            name='rci_spot_report_include_epc_uri',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='smartreader',
            name='rci_spot_report_include_inv_cnt',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='smartreader',
            name='rci_spot_report_include_pc',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='smartreader',
            name='rci_spot_report_include_phase',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='smartreader',
            name='rci_spot_report_include_prof',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='smartreader',
            name='rci_spot_report_include_range',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='smartreader',
            name='rci_spot_report_include_rssi',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='smartreader',
            name='rci_spot_report_include_rz',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='smartreader',
            name='rci_spot_report_include_scheme',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='smartreader',
            name='rci_spot_report_include_spot',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='smartreader',
            name='rci_spot_report_include_time_stamp',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='smartreader',
            name='reporting_interval_seconds',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='smartreader',
            name='require_unique_product_code',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='smartreader',
            name='software_filter_include_epcs_header_list',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='smartreader',
            name='software_filter_include_epcs_header_list_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='smartreader',
            name='software_filter_tag_id_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='smartreader',
            name='software_filter_tag_id_match',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='smartreader',
            name='software_filter_tag_id_operation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='smartreader',
            name='software_filter_tag_id_value_or_pattern',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='smartreader',
            name='tag_cache_size',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='smartreader',
            name='tag_identifier',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='smartreader',
            name='tag_presence_timeout_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='smartreader',
            name='tag_presence_timeout_in_sec',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='smartreader',
            name='toi_gpi',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='smartreader',
            name='toi_gpo_error',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='smartreader',
            name='toi_gpo_mode',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='smartreader',
            name='toi_gpo_nok',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='smartreader',
            name='toi_gpo_ok',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='smartreader',
            name='toi_gpo_priority',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='smartreader',
            name='toi_validation_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='smartreader',
            name='toi_validation_gpo_duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='smartreader',
            name='toi_validation_url',
            field=models.URLField(blank=True, max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='smartreader',
            name='update_tag_events_list_batch_on_change',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='smartreader',
            name='update_tag_events_list_batch_on_change_interval_in_sec',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='smartreader',
            name='validation_acceptance_threshold',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='smartreader',
            name='validation_acceptance_threshold_timeout',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='smartreader',
            name='write_usb_json',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='smartreader',
            name='advanced_gpo_mode_1',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='smartreader',
            name='advanced_gpo_mode_2',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='smartreader',
            name='advanced_gpo_mode_3',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='smartreader',
            name='advanced_gpo_mode_4',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='smartreader',
            name='c1g2_filter_bank',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='smartreader',
            name='c1g2_filter_len',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='smartreader',
            name='c1g2_filter_pointer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='smartreader',
            name='connection_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='smartreader',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('maintenance', 'Maintenance')], default='inactive', max_length=20),
        ),
        migrations.AlterField(
            model_name='smartreader',
            name='usb_flash_drive',
            field=models.BooleanField(default=False),
        ),
    ]
